---
kind: pipeline
type: docker
name: build

steps:
- name: test
  image: node
  commands:
    - npm ci
    - npm run build

- name: build-image
  image: docker
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - docker build . -t ${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER}

- name: mirror
  image: alpine/git
  environment:
    SSH_KEY:
      from_secret: github_credentials
  commands: 
    - mkdir ~/.ssh && echo "$SSH_KEY" > ~/.ssh/id_rsa && chmod 0600 ~/.ssh/id_rsa
    - export GIT_SSH_COMMAND="ssh -i ~/.ssh/id_rsa"
    - git clone --mirror ${DRONE_GIT_HTTP_URL}
    - cd ${DRONE_REPO_NAME}.git
    - git push --mirror git@github.com:DSchroer/drone-convert-templates.git

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
