---
kind: pipeline
type: docker
name: build

steps:
- name: test
  image: node
  commands:
    - npm ci
    - npm run build

- name: build-image
  image: docker
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - docker build . -t ${DRONE_REPO_NAME}:${DRONE_BUILD_NUMBER}

- template: github-mirror
  repo: git@github.com:DSchroer/drone-convert-templates.git

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
