---
steps:
- name: compose-deploy
  image: docker/compose:1.27.4
  volumes:
    - name: dockersock
      path: /var/run/docker.sock
  commands:
    - docker-compose build
    - docker-compose -p ${DRONE_REPO_NAME} up -d --remove-orphans

volumes:
- name: dockersock
  host:
    path: /var/run/docker.sock
